"""add transfer support to recurring rules

Revision ID: 43fc4d114134
Revises: 8cec92a8a49e
Create Date: 2026-07-26 11:59:12.958359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43fc4d114134'
down_revision = '8cec92a8a49e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_transfer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('to_account_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('amount_received', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.create_foreign_key('fk_recurring_rules_to_account_id', 'accounts', ['to_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_rules', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recurring_rules_to_account_id', type_='foreignkey')
        batch_op.drop_column('amount_received')
        batch_op.drop_column('to_account_id')
        batch_op.drop_column('is_transfer')

    # ### end Alembic commands ###
