"""add attachment_filename to transactions

Revision ID: 8cec92a8a49e
Revises: e9ec82f6e441
Create Date: 2026-07-26 01:56:21.415772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cec92a8a49e'
down_revision = 'e9ec82f6e441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('attachment_filename')

    # ### end Alembic commands ###
