"""add default_account_id to users

Revision ID: b77b5e64efd5
Revises: 58f1864a0561
Create Date: 2026-07-25 00:38:05.329244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77b5e64efd5'
down_revision = '58f1864a0561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_account_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_users_default_account_id', 'accounts', ['default_account_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_default_account_id', type_='foreignkey')
        batch_op.drop_column('default_account_id')

    # ### end Alembic commands ###
